### ISSUE TITLE
MakeCode power extension goes to sleep too quickly

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#201]
Tested on a V2.2 using the micro:bit power management extension and MakeCode live.

With this programme (more info about the programme in issue https://github.com/lancaster-university/codal-microbit-v2/issues/200), pressing button A not always shows the character `A` on the display and it goes straight into sleep.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/29712657/176004273-d54dea26-021b-419e-b0a7-578886b73e16.png">

**Comment by JohnVidler** [comment]
Placing this in the v0.2.41 release for now, mainly to facilitate tracking it

**Comment by martinwork** [comment]
I don't think this is caused by the power manager. See https://makecode.microbit.org/_f6T3709UYWij
![image](https://user-images.githubusercontent.com/989126/184494582-33a6644c-94fe-4964-b8ca-9974ce33df55.png)
When button A is pressed while the heart is big, A does not appear and the beep is short.
When button A is pressed while the heart is small, A does appear and the beep is long.
Try the same on micro:bit V1. Whenever button A is pressed, A is always displayed after the small heart and the beep is longer for a big heart press.

I think the V1/V2 difference is related to https://github.com/lancaster-university/codal-core/pull/140. The V2 sequence of events is something like this: 
- forever shows big heart and enters wait for DISPLAY_EVT_ANIMATION_COMPLETE
- button handler runs and tries to display A but sees display is busy, so enters wait for DISPLAY_EVT_FREE
- sendAnimationCompleteEvent() sends DISPLAY_EVT_ANIMATION_COMPLETE, which immediately queues forever
- sendAnimationCompleteEvent() sends DISPLAY_EVT_FREE, which immediately queues button handler after forever
- forever shows small heart and enters wait for animation DISPLAY_EVT_ANIMATION_COMPLETE
- button handler sees display is busy again and gives up here
https://github.com/lancaster-university/codal-core/blob/master/source/drivers/AnimatedDisplay.cpp#L442

Adding a pause between the hearts makes V1 and V2 match, because the button handler runs while the display is free. There is an automatic pause at the end of the forever loop. Changing to a while loop in https://github.com/lancaster-university/codal-core/pull/140 makes the handler wait until the display is actually, rather than potentially, free.

**Comment by microbit-carlos** [comment]
Thanks Martin, in that case this issue is invalid (not specific to sleep).

In issue https://github.com/lancaster-university/codal-microbit-v2/issues/95 we'll revisit the current behaviour after the https://github.com/lancaster-university/codal-core/pull/140 patch and track any additional changes required/suggested there.
