### ISSUE TITLE
`MicroBitAudio::deactivateLevelSPL()` is currently commented out

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#222]
https://github.com/lancaster-university/codal-microbit-v2/blob/13a651754e668464855fc40a81dd7dcb796b58c9/source/MicroBitAudio.cpp#L123-L125

Commented out in https://github.com/lancaster-university/codal-microbit-v2/commit/2a89bd4fee81c04ecaaef45afedb24ed02b79877, @JoshuaAHill do you remember why that was removed? Did it cause any issues?

**Comment by JohnVidler** [comment]
Not sure why its in there in the first place - the 'enabled' boolean it controls isn't used for anything as far as I can tell.

I'll shortly be adding in a `activateForEvents( bool state )` (might be renamed) which will allow users to perminently enable the component to receive onLoud/onQuiet/etc events anyway, which would seem to be the intent for the `enabled` bool but it was never hooked up?

Either way, with the addition of the new call and the demand-activation mode of the streams API, I don't think this is required anymore, unless anyone wants to put a good reason forward to include the call, rather than just swapping `deactivateLevelSPL()` to use the new `activateForEvents()` call instead?

@finneyj , opinions? Any idea why this was here?

**Comment by microbit-carlos** [comment]
Looks like it was originally added with limited functionality: https://github.com/lancaster-university/codal-core/commit/2c9bd21ddd683d48dcb46911aff3a7547905ef77

**Comment by microbit-carlos** [comment]
@JohnVidler has `deactivateLevelSPL` been removed for the upcoming v0.2.50 release?

**Comment by finneyj** [comment]
I can't think of a valid reason why we would want to keep this API, now that the microphone etc automatically enables/disables when needed. Let's take it out.

**Comment by microbit-carlos** [comment]
`MicroBitAudio::deactivateLevelSPL()` has been updated in 9734bf3a2373d0e1c74dc05bbf2fab6a4c1c64ce for v0.2.50, but I'll leave this opened and moved to the next milestone in case we want to deprecate (or remove) any of the API

**Comment by JohnVidler** [comment]
Ok, so currently this has been kept in, in case any upstream projects are using it, but we'd prefer to just remove this.

I'll sync up with Microsoft to check that they're not using it, and if not, we can pretty safely remove it.

**Comment by microbit-carlos** [comment]
Only usage we found it all of GitHub was a factory test programme example I created, so we can remove this call.
We can mark this function to deprecated and remove it in the future.

**Comment by JohnVidler** [comment]
Removed in master. If this functionality is required, the suggestion is now to use `activateForEvents( false )` instead
