### ISSUE TITLE
relocate vtor to 0x0 -> 0x20002200 0x20002200

### ISSUE THREAD

**Issue by crisgplj** [lancaster-university/codal-microbit-v2#305]
Sometimes Putty notify relocate vtor to 0x0 -> 0x20002200 0x20002200

I dont know what happens, thanks!

**Comment by microbit-carlos** [comment]
Hi @crisgplj,

That's because the debug messages were turned on by default:
https://github.com/lancaster-university/microbit-v2-samples/blob/v0.2.12/codal.json#L11-L13

If you remove those lines from `codal.json`, or pull the latest updates from https://github.com/lancaster-university/microbit-v2-samples, it should no longer print those messages to the serial.

**Comment by crisgplj** [comment]
Oh thanks you!

**Comment by microbit-carlos** [comment]
You're welcomed!
I'll close this as resolved, but don't hesitate to ask if you have any other questions 👍
