### ISSUE TITLE
Snapshot v0.2.63 points to a codal-microbit-nrf5sdk commit that is not in the repo

### ISSUE THREAD

**Issue by martinwork** [lancaster-university/codal-microbit-v2#404]
The build is showing an error.
![image](https://github.com/lancaster-university/codal-microbit-v2/assets/989126/125b43ae-8281-40ba-96d0-14eb6d58f2fb)

Snapshot v0.2.63 changed the codal-microbit-nrf5sdk commit in https://github.com/lancaster-university/codal-microbit-v2/commit/b410f946f30a9a334377d67bd72098811163b49b to point to a commit that is not in the repo https://github.com/microbit-foundation/codal-microbit-nrf5sdk/commit/5714cbe338c3544793bbb841a7ae81708a3ffae1

I guess this means the build is using the same commit as before the change, because it's the latest master commit https://github.com/microbit-foundation/codal-microbit-nrf5sdk/commit/f98e1a9325acef9de52416b3e30cc820531b6699

The change in 5714cbe is to quiet a warning. We have previously avoided making unnecessary changes to the SDK files.

**Comment by microbit-carlos** [comment]
Thanks Martin!

This turned out to be a change we wanted to revert and ended up being the head of the main branch at the time the v0.2.63 tag was created.
The commit has been added to the main branch, so that the tag is not broken when trying to rebuild in the future, and an extra commit added on top to revert it:
<img width="1313" alt="image" src="https://github.com/lancaster-university/codal-microbit-v2/assets/29712657/e9a99fb6-85f2-4de9-8706-e6e6a42a2305">

 v0.2.64 will then point to the current HEAD.
